### ISSUE TITLE
Application does not start

### ISSUE THREAD

**Issue by t4nujms** [Eugene-Mark/bigdata-file-viewer#11]
I am on Windows 10.
Following the Usage instructions in the README and get the following exception:

`C:\apps\orc_viewer>java -jar BigdataFileViewer-1.1.1-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.eugene.App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more
`

Same happens with release versions 1.2 and 1.21

I have tried copying the bins and libs for JavaFX (downloaded from https://openjfx.io/) but I am otherwise not sure how to "install" JavaFX, if that is what is needed.

My Java version is as follows:

>java --version
java 15.0.1 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

**Comment by Eugene-Mark** [comment]
@t4nujms Thanks for the response. The javafx is not bound to java 15, for your scenario, the recommended way should be [this](https://github.com/Eugene-Mark/bigdata-file-viewer/issues/7#issuecomment-744550480).
